'use strict';
const POINTS=[[.1,.12],[.5,.12],[.9,.12],[.1,.5],[.5,.5],[.9,.5],[.1,.88],[.5,.88],[.9,.88]];
const $=id=>document.getElementById(id), video=$('video'), overlay=$('overlay'), plot=$('plot'), target=$('target'), statusEl=$('status'), captureBtn=$('btn-capture'), videoWrap=document.querySelector('.video-wrap');
const octx=overlay?.getContext?.('2d')??null, pctx=plot?.getContext?.('2d')??null;
let stream=null,calibrating=false,tracking=false,pointIndex=0,samples=[],model=null,baseline=null,smooth={x:.5,y:.5};
const work=document.createElement('canvas'),wctx=work.getContext('2d',{willReadFrequently:true});
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const appReady=!!(video&&overlay&&plot&&target&&statusEl&&octx&&pctx&&wctx);
function status(t){if(statusEl)statusEl.textContent=t;}
if(video){video.setAttribute('playsinline','');video.setAttribute('muted','');video.setAttribute('autoplay','');video.playsInline=true;video.muted=true;video.autoplay=true;}
if(!appReady){console.error('No se pudo inicializar ETmobile: faltan elementos DOM/canvas.');status('Error de inicialización: faltan elementos de cámara o lienzo. Recarga la página.');}
function syncCameraBuffers(){const vw=video.videoWidth||work.width||720,vh=video.videoHeight||work.height||960;if(work.width!==vw)work.width=vw;if(work.height!==vh)work.height=vh;if(overlay.width!==vw)overlay.width=vw;if(overlay.height!==vh)overlay.height=vh;}
function lockViewport(){if(!videoWrap)return;const r=videoWrap.getBoundingClientRect();if(r.height>0){videoWrap.style.setProperty('--locked-video-height',`${r.height}px`);videoWrap.classList.add('is-calibrating');}}
function unlockViewport(){if(!videoWrap)return;videoWrap.classList.remove('is-calibrating');videoWrap.style.removeProperty('--locked-video-height');}
function placeCaptureButton([x,y]){if(!captureBtn)return;captureBtn.classList.remove('is-shift-left','is-shift-right');if(y<.78)return;if(x>.66)captureBtn.classList.add('is-shift-left');else if(x<.34)captureBtn.classList.add('is-shift-right');}
function stage(name){const items=[...document.querySelectorAll('#stage-list li')],active=items.findIndex(x=>x.dataset.stage===name);items.forEach((el,i)=>{el.classList.toggle('active',i===active);el.classList.toggle('done',i<active);});}
function metrics(e={}){$('m-cal-points').textContent=`${samples.length}/9`;$('m-rmse').textContent=model?.rmse?.toFixed(1)??'—';if(e.stability!=null)$('m-stability').textContent=`${Math.round(e.stability*100)}%`;if(e.direction)$('m-direction').textContent=e.direction;if(e.confidence!=null)$('m-confidence').textContent=`${Math.round(e.confidence*100)}%`;if(e.tracking)$('m-tracking').textContent=e.tracking;}
function cameraErrorMessage(e){switch(e?.name){case'NotAllowedError':return'Permiso de cámara denegado. Habilita la cámara en Chrome e inténtalo de nuevo.';case'NotFoundError':return'No se encontró cámara frontal disponible en este dispositivo.';case'NotReadableError':return'La cámara está ocupada por otra app o no se puede leer en este momento.';case'SecurityError':return'Chrome bloqueó la cámara por seguridad. Verifica HTTPS y permisos del sitio.';default:return`No se pudo abrir la cámara: ${e?.message??'error desconocido'}`;}}
async function startCamera(){if(!appReady)throw Error('La vista de cámara no está lista.');if(!navigator.mediaDevices?.getUserMedia)throw Error('Este navegador no soporta getUserMedia. Usa Chrome móvil actualizado en HTTPS (GitHub Pages).');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:720},height:{ideal:960}},audio:false});video.srcObject=stream;await video.play();syncCameraBuffers();stage('camera');$('btn-start-calibration').disabled=false;status('Cámara iniciada. Mantén el rostro centrado y usa luz frontal.');}
function drawTarget([x,y]){const r=overlay.getBoundingClientRect();target.style.left=`${x*r.width}px`;target.style.top=`${y*r.height}px`;target.classList.remove('hidden');placeCaptureButton([x,y]);}function hideTarget(){target.classList.add('hidden');if(captureBtn)captureBtn.classList.remove('is-shift-left','is-shift-right');}
function features(){
if(!video.videoWidth)return null;
wctx.drawImage(video,0,0,work.width,work.height);
const id=wctx.getImageData(0,0,work.width,work.height),gray=new Uint8Array(work.width*work.height);
for(let i=0;i<gray.length;i++)gray[i]=(0.299*id.data[i*4]+0.587*id.data[i*4+1]+0.114*id.data[i*4+2])|0;
const fx=work.width*.18,fy=work.height*.12,fw=work.width*.64,fh=work.height*.76,boxes=[{x:fx+fw*.18,y:fy+fh*.28,w:fw*.24,h:fh*.2},{x:fx+fw*.58,y:fy+fh*.28,w:fw*.24,h:fh*.2}],eyes=boxes.map(b=>{let sx=0,sy=0,sw=0;for(let y=Math.max(0,b.y|0);y<Math.min(work.height,(b.y+b.h)|0);y++)for(let x=Math.max(0,b.x|0);x<Math.min(work.width,(b.x+b.w)|0);x++){const d=255-gray[y*work.width+x];if(d>30){sx+=x*d;sy+=y*d;sw+=d;}}return sw?{x:sx/sw,y:sy/sw}:null;});
if(!eyes[0]||!eyes[1])return null;
return{left:eyes[0],right:eyes[1],boxes,face:{x:fx,y:fy,width:fw,height:fh},v:[1,(eyes[0].x-boxes[0].x)/boxes[0].w,(eyes[0].y-boxes[0].y)/boxes[0].h,(eyes[1].x-boxes[1].x)/boxes[1].w,(eyes[1].y-boxes[1].y)/boxes[1].h,(fx+fw/2)/work.width,(fy+fh/2)/work.height,(fw*fh)/(work.width*work.height)]};
}
function solve(A,b){const n=A.length,M=A.map((r,i)=>[...r,b[i]]);for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(M[r][c])>Math.abs(M[p][c]))p=r;[M[c],M[p]]=[M[p],M[c]];if(Math.abs(M[c][c])<1e-9)return null;for(let r=c+1;r<n;r++){const f=M[r][c]/M[c][c];for(let j=c;j<=n;j++)M[r][j]-=f*M[c][j];}}const x=Array(n).fill(0);for(let i=n-1;i>=0;i--){x[i]=M[i][n];for(let j=i+1;j<n;j++)x[i]-=M[i][j]*x[j];x[i]/=M[i][i];}return x;}
const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
function fit(){const d=8,X=Array.from({length:d},()=>Array(d).fill(0)),bx=Array(d).fill(0),by=Array(d).fill(0);for(const s of samples)for(let i=0;i<d;i++){bx[i]+=s.f.v[i]*s.p[0];by[i]+=s.f.v[i]*s.p[1];for(let j=0;j<d;j++)X[i][j]+=s.f.v[i]*s.f.v[j];}for(let i=0;i<d;i++)X[i][i]+=.06;const wx=solve(X.map(r=>[...r]),bx),wy=solve(X.map(r=>[...r]),by);if(!wx||!wy)return null;let e=0;for(const s of samples)e+=(dot(wx,s.f.v)-s.p[0])**2+(dot(wy,s.f.v)-s.p[1])**2;return{wx,wy,rmse:Math.sqrt(e/samples.length)*Math.min(innerWidth,innerHeight)};}
function gaze(f){return{x:clamp(dot(model.wx,f.v)),y:clamp(dot(model.wy,f.v))};}function direction(x,y){const h=x<.38?'izquierda':x>.62?'derecha':'centro',v=y<.38?'arriba':y>.62?'abajo':'centro';return h==='centro'&&v==='centro'?'Centro':h==='centro'?v:v==='centro'?h:`${v}-${h}`;}
function draw(f,g,stable=true){octx.clearRect(0,0,overlay.width,overlay.height);if(!f)return;octx.strokeStyle=stable?'#5eff9f':'#ff955e';octx.strokeRect(f.face.x,f.face.y,f.face.width,f.face.height);octx.strokeStyle='#6ba9ff';f.boxes.forEach(b=>octx.strokeRect(b.x,b.y,b.w,b.h));octx.fillStyle='#ffcf5e';[f.left,f.right].forEach(p=>{octx.beginPath();octx.arc(p.x,p.y,4,0,Math.PI*2);octx.fill();});if(g){octx.strokeStyle='#fff';const x=g.x*overlay.width,y=g.y*overlay.height;octx.beginPath();octx.moveTo(x-10,y);octx.lineTo(x+10,y);octx.moveTo(x,y-10);octx.lineTo(x,y+10);octx.stroke();}}
function plotGaze(g){pctx.fillStyle='#0d1117';pctx.fillRect(0,0,plot.width,plot.height);pctx.strokeStyle='#2d3b50';pctx.strokeRect(14,14,plot.width-28,plot.height-28);pctx.beginPath();pctx.moveTo(plot.width/2,14);pctx.lineTo(plot.width/2,plot.height-14);pctx.moveTo(14,plot.height/2);pctx.lineTo(plot.width-14,plot.height/2);pctx.stroke();pctx.fillStyle='#58a6ff';pctx.beginPath();pctx.arc(14+g.x*(plot.width-28),14+g.y*(plot.height-28),8,0,Math.PI*2);pctx.fill();}
function stability(f){const cx=f.v[5],cy=f.v[6],area=f.v[7];if(!baseline){baseline={cx,cy,area};return 1;}return clamp(1-(Math.hypot(cx-baseline.cx,cy-baseline.cy)*9+Math.abs(area-baseline.area)/Math.max(baseline.area,.0001)*1.6));}
async function capture(){if(!calibrating)return;const f=features();if(!f){status('No se detectan los ojos. Ajusta luz y encuadre.');return;}const s=stability(f);metrics({stability:s});if(s<.55){status('Cabeza inestable. Quédate quieto/a y repite.');return;}samples.push({f,p:POINTS[pointIndex++]});metrics();if(pointIndex===POINTS.length){calibrating=false;hideTarget();$('btn-capture').disabled=true;model=fit();if(!model||model.rmse>180){status('Calibración de baja calidad. Repite con mejor luz.');return;}$('btn-start-tracking').disabled=false;stage('tracking');status('Calibración completa. Inicia el seguimiento.');}else{drawTarget(POINTS[pointIndex]);status(`Punto ${pointIndex+1}/9: fija la mirada y captura.`);}}
async function loop(){if(!tracking)return;const f=features();if(!f){metrics({tracking:'Sin detección',confidence:0});requestAnimationFrame(loop);return;}const s=stability(f),g=gaze(f);smooth.x=smooth.x*.75+g.x*.25;smooth.y=smooth.y*.75+g.y*.25;const conf=clamp(s*.7+.3);draw(f,smooth,s>=.5);if(s>=.5){plotGaze(smooth);stage('results');}metrics({stability:s,direction:direction(smooth.x,smooth.y),confidence:conf,tracking:s>=.5?'Activo':'Pausado por movimiento'});requestAnimationFrame(loop);}
if(appReady){$('btn-start-camera').onclick=()=>startCamera().catch(e=>status(cameraErrorMessage(e)));$('btn-start-calibration').onclick=()=>{syncCameraBuffers();calibrating=true;pointIndex=0;samples=[];baseline=null;stage('calibration');lockViewport();$('btn-capture').disabled=false;drawTarget(POINTS[0]);status('Mira el punto y captura cuando estés quieto/a.');metrics();};$('btn-capture').onclick=capture;$('btn-start-tracking').onclick=()=>{if(!model)return;tracking=true;stage('tracking');status('Seguimiento activo.');loop();};$('btn-reset').onclick=()=>{tracking=calibrating=false;pointIndex=0;samples=[];model=null;baseline=null;unlockViewport();hideTarget();octx.clearRect(0,0,overlay.width,overlay.height);smooth={x:.5,y:.5};plotGaze(smooth);stage(stream?'camera':'intro');metrics({tracking:'Inactivo',confidence:0,stability:0,direction:'—'});status('Sesión reiniciada.');};video.addEventListener('loadedmetadata',syncCameraBuffers);window.addEventListener('resize',()=>{if(!calibrating)unlockViewport();if(calibrating)lockViewport();});window.addEventListener('beforeunload',()=>stream?.getTracks().forEach(t=>t.stop()));stage('intro');plotGaze(smooth);metrics({tracking:'Inactivo',confidence:0,stability:0,direction:'—'});}
